INFO:extensions:All Flask extensions initialized successfully
INFO:werkzeug: * Restarting with stat
INFO:extensions:All Flask extensions initialized successfully
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 407-421-330
(3899) wsgi starting up on http://0.0.0.0:5000
(3899) accepted ('172.31.196.163', 33728)
Traceback (most recent call last):
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask_login/login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask/helpers.py", line 232, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/TornadoChatRoom/.pythonlibs/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'login' instead?
209.237.113.2,10.82.2.24,172.31.196.163 - - [11/Dec/2024 15:35:30] "GET / HTTP/1.1" 500 26823 0.010041
209.237.113.2,10.82.2.24,172.31.196.163 - - [11/Dec/2024 15:35:30] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 159 0.004430
209.237.113.2,10.82.3.33,172.31.196.163 - - [11/Dec/2024 15:35:30] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 160 0.000614